syntax = "proto3";

option csharp_namespace = "Veeam.AC.Service.PluginManager";

message PluginManifest {
	int32 manifestVersion = 1; // version of format of manifest
	string pluginId = 2; // UUID of plugin.
	string packageId = 3; // Nuget package id of plugin. Example. MyPlugin.Organization.Com
	string name = 4; // Display name of plugin.
	string icon = 5; // Path to icon of plugin. It should be available to be requested from plugin via HTTP.
	string description = 6; // Description of plugin.
	string version = 7; // Nuget package version of plugin.
	
	repeated PluginFile files = 8; // List of all files available to requested from plugin via HTTP.

	int32 serviceHttpPort = 9; // TCP port of service part of plugin which should answer to HTTP requests.
	string serviceExecutableName = 10; // file name (not a path!) of executable file of service for 'outProcess' hosting.
	string serviceStartArguments = 11; // start arguments for service executable.
	string serviceOsServiceName = 12; // name of OS service in case of 'osService' hosting.
	PluginHosting serviceHosting = 13; // type of hosting of service part of plugin.
	PluginApiKeyObtainMethod serviceApiKeyObtainMethod = 19; // way of obtaining VSPC REST API key for plugin.

	string serviceHealthCheckUrl = 14; // service health check endpoint path
	string serviceReadinessCheckUrl = 15; // service readiness check endpoint path
	string servicePurgeDataRequestUrl = 20; // service purge data endpoint path 
	string serviceLogDownloadRequestUrl = 21; // service log download endpoint path
	bool serviceUseDb = 16; // if service required DB connection string for functioning.

	string agentExecutableName = 17; // file name (not a path!) of executable file of agent.
	string agentStartArguments = 18; // start arguments for agent executable.
}

enum PluginHosting {
	external = 0; // plugin is started/stopped by other means ourside of VSPC control.
	outProcess = 1; // plugin is started/stopped from executable by VSPC.
	osService = 2; // plugin is started/stopped by OS service name by VSPC.
}

enum PluginApiKeyObtainMethod {
	none = 0; // no REST API key is required by plugin.
	autoGenerated = 1; // REST API key should be generated on install for plugin.
	givenByAdmin = 2; // REST API key should be provided by administrator during on installation.
}

message PluginFile {
	string path = 1; // relating path to file.
	string sha1Hash = 2; // SHA-1 hash of file.
	string sha256Hash = 3; // SHA-256 of file.
	PluginFilePurpose purpose = 4; // Purpose of file.
}

enum PluginFilePurpose {
	uiContent = 0; // UI-related file. Images, fonts goes here.
	uiScript = 1; // UI-related scripts which should be loaded to VSPC UI page.
	uiLayoutConfig = 2; // JSON contiguration file for UI page.
	restSpecification = 3; // Open API REST specification file of plugin. Only REST endpoing declared in this specification would be proxied to plugin.
	grpcSpecification = 4; // GRPC API specification file used to comminicate with Agent.
	jsonRpcSpecification = 5; // JSON API specification file used to comminicate with Agent.
	serviceContent = 6; // Plugin service related file.
	agentContent = 7; // Plugin agent related file.
}